{{- $values := $.Values }}
{{- $componentName := "server" }}
{{- $componentLabel := include "dshackle.componentLabelFor" $componentName }}
{{- /* If serviceMonitors enabled in chart-wide values */ -}}
{{- if $.Values.prometheus.serviceMonitors.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "dshackle.fullname" . }}-{{ $componentName }}
  labels:
    {{- include "dshackle.labels" . | nindent 4 }}
    {{- $componentLabel | nindent 4 }}
spec:
  jobLabel: "{{ .Release.Name }}"
  selector:
    matchLabels:
      {{- include "dshackle.selectorLabels" . | nindent 6 }}
      {{- $componentLabel | nindent 6 }}
  endpoints:
    - port: http-metrics
      {{- with .Values.prometheus.serviceMonitors.interval }}
      interval: {{ . }}
      path: '/metrics'
      {{- end }}
      {{- with .Values.prometheus.serviceMonitors.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
      honorLabels: true
      {{- if .Values.prometheus.serviceMonitors.relabelings }}
      relabelings:
      {{- toYaml .Values.prometheus.serviceMonitors.relabelings | nindent 8 }}
      {{- end }}
    {{- if $values.lruCache.enabled }}
    - port: http-rmetrics
      {{- with .Values.prometheus.serviceMonitors.interval }}
      interval: {{ . }}
      path: '/metrics'
      {{- end }}
      {{- with .Values.prometheus.serviceMonitors.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
      honorLabels: true
      {{- if .Values.prometheus.serviceMonitors.relabelings }}
      relabelings:
      {{- toYaml .Values.prometheus.serviceMonitors.relabelings | nindent 8 }}
      {{- end }}
    {{- end }}
{{- end }}